# Generated by Django 4.2.5 on 2023-09-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_card_updated_at_alter_card_autor_alter_card_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='priority',
            field=models.CharField(choices=[('1', 'Baixa'), ('2', 'Média'), ('3', 'Alta')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('todo', 'To do'), ('inprogress', 'In progress'), ('done', 'Done')], default='todo', max_length=11),
        ),
    ]
