# Generated by Django 4.2.5 on 2023-09-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_card_priority_alter_card_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
