# Generated by Django 4.2.5 on 2023-09-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_card_completed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='text',
            new_name='description',
        ),
    ]
